#include "golden_config.h"
// 外部传入
std::string golden_config::task_name_;
std::vector<std::string> golden_config::host_name_;
int golden_config::port_;
std::string golden_config::user_;
std::string golden_config::password_;
std::string golden_config::start_time_;
std::string golden_config::end_time_;
int golden_config::elapse_time_;
int golden_config::increment_time_;
bool golden_config::put_history_data_;
int golden_config::min_value_;
int golden_config::max_value_;
std::string golden_config::generator_;
std::string golden_config::search_condition_;
int golden_config::first_point_;
int golden_config::point_count_;
int golden_config::point_interval_;
std::string golden_config::write_mode_;
int golden_config::threadcount_;
bool golden_config::print_log_;
int golden_config::log_level_;
int golden_config::func_period_;
std::string golden_config::result_file_;

// 内部转换
int golden_config::start_time_int_;
int golden_config::end_time_int_;
